### ISSUE TITLE
Uncaught TypeError: FocusTrap.activate is not a function

### ISSUE THREAD

**Issue by alexzeng2014** [puranjayjain/chrome-color-picker#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [chrome-color-picker](https://github.com/puranjayjain/chrome-color-picker) package, v0.8.0
### Stack Trace

Uncaught TypeError: FocusTrap.activate is not a function

```
At /C:/Users/alexzeng/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:1007

TypeError: FocusTrap.activate is not a function
    at Object.module.exports.CCP.setTrap (file:///C:/Users/alexzeng/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:942:15)
    at Object.module.exports.CCP.toggle (file:///C:/Users/alexzeng/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:325:8)
    at atom-workspace.subscriptions.add.atom.commands.add.chrome-color-picker:toggle (file:///C:/Users/alexzeng/.atom/packages/chrome-color-picker/lib/chrome-color-picker.coffee:137:94)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\alexzeng\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\alexzeng\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\alexzeng\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\alexzeng\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\alexzeng\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\alexzeng\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
     -2:26.4.0 core:paste (atom-text-editor.editor.is-focused)
     -2:23.1.0 core:save (atom-text-editor.editor.is-focused)
     -2:04.4.0 core:copy (atom-text-editor.editor.is-focused)
     -2:01.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:01.3.0 core:paste (atom-text-editor.editor.is-focused)
     -1:58.9.0 core:save (atom-text-editor.editor.is-focused)
     -1:35.9.0 chrome-color-picker:toggle (atom-text-editor.editor.is-focused)
     -0:12.4.0 core:copy (atom-text-editor.editor.hex.mini.is-focused)
     -0:03.1.0 chrome-color-picker:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "color-picker"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "chrome-color-picker": {
    "General": {}
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.9
atom-html-preview, v0.1.21
atom-material-ui, v1.2.13
chrome-color-picker, v0.8.0
emmet, v2.4.3
file-icons, v1.7.15
markdown-scroll-sync, v2.1.2
minimap, v4.24.6

# Dev
No dev packages
```

**Comment by puranjayjain** [comment]
@alexzeng2014 thanks for reporting this issue, I recently bumped the version of focus trap to v2 so it shall be fixed in the next release. Although I cant give any eta at the moment.
