### ISSUE TITLE
Uncaught Error: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by Timemashine** [puranjayjain/chrome-color-picker#11]
1. Awesome Package! Thank you  ![](https://static-cdn.jtvnw.net/emoticons/v1/64138/1.0)
2. Open the Color Picker in any File
3. Klick on the "Pick Color" Icon
4. Move the cursor

> The Circle don't move with the cursor or with a huge delay.

**Atom Version**: 1.9.8
**System**: Mac OS X 10.12
**Thrown From**: [chrome-color-picker](https://github.com/puranjayjain/chrome-color-picker) package, v0.8.0
### Stack Trace

Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    `at emitTwo (events.js:100:13)` 
    at EventEmitter.emit (events.js:185:7)

```
At /Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178

Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (/Applications/Atom.app/Contents/Resources/electron.asar/browser/objects-registry.js:44:28)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/rpc-server.js:309:31)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/electron.asar/browser/api/web-contents.js:141:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at metaToValue (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:178:13)
    at undefined.remoteMemberFunction (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/api/remote.js:112:18)
    at ApplicationDelegate.module.exports.ApplicationDelegate.getWindowSize (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:52:41)
    at AtomEnvironment.module.exports.AtomEnvironment.getSize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:544:39)
    at updateUI (~/.atom/packages/chrome-color-picker/lib/modules/core/Picker.coffee:46:27)
```
### Commands

```
     -3:42.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:32.8.0 key-binding-resolver:toggle (atom-text-editor.editor.mini.is-focused)
     -3:29 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -1:00.6.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:33.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:33 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:32.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:25.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:23.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:16.7.0 chrome-color-picker:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "automaticallyUpdate": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "tool-bar-main",
      "php-debug",
      "project-view",
      "project-environment",
      "native-color-picker",
      "preview-plus",
      "php-refactoring",
      "php-cs-fixer",
      "autohide-tree-view",
      "symbols-tree-view",
      "atom-ftp-deployment"
    ],
    "packagesWithKeymapsDisabled": [
      "git-plus"
    ],
    "themes": [
      "one-dark-ui",
      "monokai-fresh-syntax"
    ]
  },
  "chrome-color-picker": {
    "General": {
      "showButtons": true
    },
    "HexColors": {}
  }
}
```
### Installed Packages

``` coffee
# User
advanced-open-file, v0.16.3 (inactive)
aesthetic-ui, v2.0.0 (inactive)
atom-ftp-deployment, v0.4.0 (inactive)
atom-html-preview, v0.1.22 (active)
autohide-tree-view, v0.25.1 (inactive)
bottom-dock, v0.4.4 (active)
browser-plus, v0.0.76 (active)
chrome-color-picker, v0.8.0 (active)
diff-pane, v0.1.0 (inactive)
drunken-php, v0.2.2 (active)
expose, v0.12.1 (inactive)
file-icons, v1.7.18 (active)
genesis-ui, v0.5.0 (inactive)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
hyperclick-php, v0.2.1 (active)
language-csv, v1.1.2 (active)
language-htaccess, v0.1.1 (active)
linter, v1.11.16 (active)
linter-php, v1.2.0 (active)
man, v0.5.0 (inactive)
markdown-preview-plus, v2.4.0 (active)
minimap, v4.24.7 (active)
monokai-fresh-syntax, v0.0.2 (active)
native-color-picker, v0.2.0 (inactive)
native-ui, v0.18.3 (inactive)
nucleus-dark-ui, v0.9.1 (inactive)
number-slider, v1.0.1 (active)
on-save, v0.2.9 (active)
php-cs-fixer, v2.5.9 (inactive)
php-debug, v0.2.3 (inactive)
php-integrator-annotations, v1.0.1 (active)
php-integrator-autocomplete-plus, v1.0.4 (active)
php-integrator-base, v1.1.2 (active)
php-integrator-call-tips, v1.0.1 (active)
php-integrator-linter, v1.1.0 (active)
php-integrator-navigation, v1.0.2 (active)
php-integrator-refactoring, v1.1.0 (active)
php-integrator-symbol-viewer, v0.6.4 (active)
php-integrator-tooltips, v1.0.1 (active)
php-refactoring, v1.4.0 (inactive)
preview-plus, v1.2.7 (inactive)
project-environment, v1.0.4 (inactive)
project-manager, v2.9.7 (active)
project-plus, v0.9.0 (active)
project-view, v0.5.0 (inactive)
quick-query, v0.8.4 (inactive)
Remote-FTP, v0.8.3 (active)
symbols-list, v2.3.0 (active)
symbols-tree-view, v0.13.2 (inactive)
table-editor, v0.2.0 (active)
tablr, v1.3.2 (active)
term3, v0.22.1 (active)
tool-bar, v1.0.1 (active)
tool-bar-basic, v1.1.2 (active)
tool-bar-main, v0.0.9 (inactive)
tree-view-git-status, v1.1.0 (active)
tree-view-open-files, v0.3.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by puranjayjain** [comment]
@Timemashine thanks I have been aware of this bug for quite some time I haven;t been able to work in it for some time though. I will resume work when I get the time and fix it. Meanwhile feel free to PR if you can I have written some ways it can be fixed in the wiki
