### ISSUE TITLE
Failed to activate the chrome-color-picker package

### ISSUE THREAD

**Issue by vladgohn** [puranjayjain/chrome-color-picker#17]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [chrome-color-picker](https://github.com/puranjayjain/chrome-color-picker) package 0.8.0

### Stack Trace

Failed to activate the chrome-color-picker package

```
At JSTabber is not a constructor

TypeError: JSTabber is not a constructor
    at Palette.module.exports.Palette.initPopupPalette (/packages/chrome-color-picker/lib/modules/core/Palette.coffee:170:20)
    at /packages/chrome-color-picker/lib/modules/core/Palette.coffee:59:22)
    at Object.activate (/packages/chrome-color-picker/lib/chrome-color-picker.coffee:87:19)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/app.asar/src/atom-environment.js:1185:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -9:53.8.0 core:confirm (input.hidden-input)
     -9:24.2.0 find-and-replace:replace-next (table.native-key-bindings.table.text)
     -8:57.6.0 tree-view:toggle-focus (input.hidden-input)
  5x -8:38.6.0 core:backspace (input.hidden-input)
     -8:33.7.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-one-light-ui)
  2x -8:00.4.0 core:confirm (input.hidden-input)
     -5:24.8.0 core:paste (input.hidden-input)
     -4:02.9.0 color-picker:open (input.hidden-input)
     -3:38.3.0 core:backspace (input.hidden-input)
     -3:38 core:confirm (input.hidden-input)
  2x -2:33.1.0 color-picker:open (input.hidden-input)
  5x -2:12.7.0 native-color-picker:pick (span.syntax--constant.syntax--other.syntax--rgb-value.syntax--css)
     -0:21.1.0 chrome-color-picker:toggle (span.syntax--constant.syntax--other.syntax--rgb-value.syntax--css)
```

### Non-Core Packages

```
chrome-color-picker 0.8.0 
color-picker 2.2.5 
emmet 2.4.3 
pigments 0.39.1 
```

**Comment by puranjayjain** [comment]
the package has not been upgraded to work with atom 1.x and its apis and hence has stopped working. I'm working to get it done asap
