### ISSUE TITLE
Uncaught Error: You can't have a focus-trap without at least one focusable element

### ISSUE THREAD

**Issue by StevenPeeters** [puranjayjain/chrome-color-picker#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [chrome-color-picker](https://github.com/puranjayjain/chrome-color-picker) package 0.8.0

### Stack Trace

Uncaught Error: You can't have a focus-trap without at least one focusable element

```
At /Users/Steven/.atom/packages/chrome-color-picker/lib/modules/helper/FocusTrap.coffee:30

Error: You can't have a focus-trap without at least one focusable element
    at firstFocusNode (/packages/chrome-color-picker/lib/modules/helper/FocusTrap.coffee:30:13)
    at Object.activate (/packages/chrome-color-picker/lib/modules/helper/FocusTrap.coffee:17:12)
    at Object.setTrap (/packages/chrome-color-picker/lib/chrome-color-picker.coffee:942:15)
    at Object.toggle (/packages/chrome-color-picker/lib/chrome-color-picker.coffee:325:8)
    at /packages/chrome-color-picker/lib/chrome-color-picker.coffee:137:94)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:197:7)
```

### Commands

```
     -1:29.9.0 application:reopen-project (input.hidden-input)
     -1:24.5.0 datatip:toggle (input.hidden-input)
     -1:24 datatip:copy-to-clipboard (input.hidden-input)
  3x -1:23.3.0 datatip:toggle (input.hidden-input)
     -1:20.2.0 datatip:copy-to-clipboard (input.hidden-input)
     -1:19.7.0 datatip:toggle (input.hidden-input)
     -1:16.8.0 code-format:format-code (input.hidden-input)
  2x -1:13.3.0 datatip:toggle (input.hidden-input)
     -1:10.7.0 core:undo (input.hidden-input)
     -1:08.9.0 editor:copy-path (input.hidden-input)
  2x -1:06.3.0 datatip:toggle (input.hidden-input)
     -1:01.5.0 core:undo (input.hidden-input)
  3x -0:59.3.0 datatip:toggle (input.hidden-input)
     -0:57 code-format:format-code (input.hidden-input)
     -0:22.5.0 chrome-color-picker:toggle (span.syntax--constant.syntax--other.syntax--color.syntax--rgb-value.syntax--hex.syntax--css)
```

### Non-Core Packages

```
atom-ide-ui 0.12.0 
chrome-color-picker 0.8.0 
ide-cpp 0.0.3 
ide-css 0.3.0 
ide-html 0.4.2 
ide-json 0.2.1 
ide-python 0.9.2 
ide-vue 0.1.8 
language-vue 0.23.1 
rbox 0.5.0 
vue-autocomplete 0.1.1 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by puranjayjain** [comment]
Thanks fr reporting this bug! Will need to update to a newer version of focus trap and atom package ui. Feel free to raise a PR in case you find a quicker solution
